### PR TITLE
Add @min and @max to number inputs 

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by remy** [comment]
I purposely prevented that to allow the user to spin higher than the range element. Do you think they shouldn't be able to (or have you spotted a bug that I've not seen yet)?

**Comment by mathiasbynens** [comment]
Oh, I just noticed you use the little buttons next to `input[type=number]` to lower the value even below zero. I can drop the `max` attribute from the pull request if you want, but please consider adding `min=0` (or `min=10`) :)

**Comment by remy** [comment]
min=0 - good point. Tweak the merge and I'll pull it in - I'll get your sexier than you analytics code too :)

**Comment by mathiasbynens** [comment]
Done!

**Comment by remy** [comment]
...and live :)

**Comment by mathiasbynens** [comment]
`\o/`

**Pull request merged**
